channels:

  - name: "Channel 1"
    input:
      type: "udp_server"
      port: 8001
    output:
      type: "serial"
      serial_port: "/dev/ttyS0"
      baud_rate: 9600

  - name: "Channel 2"
    input:
      type: "tcp_server"
      port: 8001
    output:
      type: "tcp_client"
      ip: "192.168.145.1"
      port: 8002