channels:

  - name: "Channel 1"
    input:
      type: "tcp_client"
      ip: "172.16.24.69"
      port: 8001
    output:
      type: "udp_server"
      port: 8080

  - name: "Channel 2"
    input:
      type: "udp_server"
      port: 8081
    output:
      type: "tcp_client"
      ip: "172.16.24.129"
      port: 600
      
  - name: "Channel 3"
    input:
      type: "tcp_server"
      port: 8070
    output:
      type: "udp_server"
      port: 8082

  - name: "Channel 4"
    input:
      type: "udp_client"
      ip: "172.16.24.69"
      port: 8080
    output:
      type: "tcp_server"
      port: 8071
  
  - name: "Channel 5"
    input:
      type: "tcp_server"
      port: 8072
    output:
      type: "udp_client"
      ip: "172.16.24.129"
      port: 500
  # - name: "Channel 6"
  #   input:
  #     type: "tcp_server"
  #     port: 7001
  #   output:
  #     type: "tcp_server"
  #     port: 9001
  # - name: "Channel 7"
  #   input:
  #     type: "tcp_server"
  #     port: 7002
  #   output:
  #     type: "tcp_server"
  #     port: 9002

  # - name: "Channel 8"
  #   input:
  #     type: "tcp_server"
  #     port: 7003
  #   output:
  #     type: "tcp_server"
  #     port: 9003

  - name: "Channel 9"
    input:
      type: "tcp_server"
      port: 7004
    output:
      type: "tcp_server"
      port: 9004
  - name: "Channel 10"
    input:
      type: "tcp_server"
      port: 7005
    output:
      type: "tcp_server"
      port: 9005
  - name: "Channel 11"
    input:
      type: "tcp_server"
      port: 7006
    output:
      type: "tcp_server"
      port: 9006
  - name: "Channel 12"
    input:
      type: "tcp_server"
      port: 7007
    output:
      type: "tcp_server"
      port: 9007
  