channels:

  - name: "Channel 1"
    input:
      type: "tcp_client"
      ip: "192.168.43.1"
      port: 8001
    output:
      type: "tcp_server"
      port: 8080

  - name: "Channel 2"
    input:
      type: "tcp_server"
      port: 8090
    output:
      type: "tcp_client"
      ip: "192.168.43.1"
      port: 8002
